dist: bionic
language: minimal
addons:
  apt:
    packages:
      - parallel
install:
  - chmod +x dup.sh
  - chmod +x test.sh
script:
  - ./test_prepare.sh
  - rm -rf .dup.moved_files
  - ./test_move.sh
  - rm -rf .dup.moved_files
  - ./test_delete.sh
